### ISSUE TITLE
Error after fork

### ISSUE THREAD

**Issue by restrepo** [mrtrkmnhub/latex-on-ci-cd#1]
Hi
After making a fork of this repository,  and authorize the Action, when I try to create a release with some tag, e.g 2.0.0, I got the following error:

```
Error: Validation Failed: {"resource":"Release","code":"already_exists","field":"tag_name"}
```

See the log at:

https://github.com/restrepo/latex-on-ci-cd/runs/2062399073?check_suite_focus=true

Do you know hot I could fix the Error?

UPDATE:
The release must be created from the local clone with:
```bash 
$ git tag v2.0.0
$ git push --tags
```

Thanks
:D

**Comment by mrtrkmn** [comment]
Hi @restrepo 
I think, you have solved the issue ? 
Otherwise, mention me regarding to it.

**Comment by restrepo** [comment]
Yes, I did resolve the issue by making the release from the local clone instead than directly from GitHub

**Comment by mrtrkmn** [comment]
Thanks @restrepo. 
I am closing the issue.
